Repository highFour-LUMO/LUMO_BE, pull requests merged in 2025-03, with the labels that each got.

#10 feat : 이메일 인증
  .DS_Store
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  build.gradle
  src/main/java/com/highFour/LUMO/member/config/SecurityConfig.java
  src/main/java/com/highFour/LUMO/member/controller/MemberController.java
  src/main/java/com/highFour/LUMO/member/jwt/service/JwtService.java
  src/main/java/com/highFour/LUMO/member/oauth2/OAuthAttributes.java
  src/main/java/com/highFour/LUMO/member/smtp/config/EmailConfig.java
  src/main/java/com/highFour/LUMO/member/smtp/contorller/EmailController.java
  src/main/java/com/highFour/LUMO/member/smtp/dto/EmailCheckReq.java
  src/main/java/com/highFour/LUMO/member/smtp/dto/EmailSendReq.java
  src/main/java/com/highFour/LUMO/member/smtp/service/EmailService.java
  src/main/java/com/highFour/LUMO/member/smtp/util/RedisUtil.java
  src/main/resources/application.yml
Labels: ✨ feature

#8 feat: 일기 삭제, 조회
  .github/workflows/AutomaticAssignReviewers.yml
  HELP.md
  src/main/java/com/highFour/LUMO/common/domain/BaseTimeEntity.java
  src/main/java/com/highFour/LUMO/diary/api/DiaryController.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryCreateReq.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryDetRes.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryListRes.java
  src/main/java/com/highFour/LUMO/diary/dto/DiarySearchReq.java
  src/main/java/com/highFour/LUMO/diary/entity/Diary.java
  src/main/java/com/highFour/LUMO/diary/repository/DiaryRepository.java
  src/main/java/com/highFour/LUMO/diary/service/DiaryService.java
  src/main/java/com/highFour/LUMO/member/controller/MemberController.java
  src/main/java/com/highFour/LUMO/member/jwt/service/JwtService.java
  src/main/resources/application.yml
Labels: ✨ feature

#13 feat: 일기 평점 기능
  src/main/java/com/highFour/LUMO/common/exceptionType/DiaryExceptionType.java
  src/main/java/com/highFour/LUMO/diary/api/DiaryController.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryCreateReq.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryDetRes.java
  src/main/java/com/highFour/LUMO/diary/entity/Diary.java
  src/main/java/com/highFour/LUMO/diary/repository/DiaryRepository.java
  src/main/java/com/highFour/LUMO/diary/service/DiaryService.java
Labels: ✨ feature

#17 feat: 로그인한 회원의 친구 목록 조회
  .DS_Store
  src/main/java/com/highFour/LUMO/common/exceptionType/FriendExceptionType.java
  src/main/java/com/highFour/LUMO/friend/api/FriendController.java
  src/main/java/com/highFour/LUMO/friend/dto/FriendListRes.java
  src/main/java/com/highFour/LUMO/friend/entity/Friend.java
  src/main/java/com/highFour/LUMO/friend/repository/FriendRepository.java
  src/main/java/com/highFour/LUMO/friend/service/FriendService.java
Labels: ✨ feature

#18 feat: 회원 관리
  src/main/java/com/highFour/LUMO/common/exceptionType/MemberExceptionType.java
  src/main/java/com/highFour/LUMO/common/handler/GlobalExceptionHandler.java
  src/main/java/com/highFour/LUMO/common/response/CustomErrorResponse.java
  src/main/java/com/highFour/LUMO/member/api/MemberController.java
  src/main/java/com/highFour/LUMO/member/config/SecurityConfig.java
  src/main/java/com/highFour/LUMO/member/dto/MemberInfoRes.java
  src/main/java/com/highFour/LUMO/member/dto/MemberPasswordResetReq.java
  src/main/java/com/highFour/LUMO/member/dto/MemberPasswordUpdateReq.java
  src/main/java/com/highFour/LUMO/member/dto/MemberSignUpReq.java
  src/main/java/com/highFour/LUMO/member/dto/MemberUpdateInfoReq.java
  src/main/java/com/highFour/LUMO/member/dto/SignUpReq.java
  src/main/java/com/highFour/LUMO/member/entity/Member.java
  src/main/java/com/highFour/LUMO/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/highFour/LUMO/member/jwt/service/JwtService.java
  src/main/java/com/highFour/LUMO/member/login/handler/LoginSuccessHandler.java
  src/main/java/com/highFour/LUMO/member/repository/MemberRepository.java
  src/main/java/com/highFour/LUMO/member/service/MemberService.java
  src/main/java/com/highFour/LUMO/member/smtp/api/EmailController.java
  src/main/java/com/highFour/LUMO/member/smtp/service/EmailService.java
  src/main/java/com/highFour/LUMO/member/smtp/util/RedisUtil.java
  src/main/resources/static/index.html
Labels: ✨ feature

#16 feat: 일기 수정 및 API 수정
  src/main/java/com/highFour/LUMO/common/exceptionType/DiaryExceptionType.java
  src/main/java/com/highFour/LUMO/diary/api/DiaryController.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryUpdateReq.java
  src/main/java/com/highFour/LUMO/diary/entity/Diary.java
  src/main/java/com/highFour/LUMO/diary/repository/DiaryRepository.java
  src/main/java/com/highFour/LUMO/diary/service/DiaryService.java
Labels: ✨ feature

#25 feat: 친구 요청 수락 / 거절 기능 구현
  src/main/java/com/highFour/LUMO/common/exceptionType/FriendExceptionType.java
  src/main/java/com/highFour/LUMO/friend/api/FriendController.java
  src/main/java/com/highFour/LUMO/friend/entity/FriendRequest.java
  src/main/java/com/highFour/LUMO/friend/repository/FriendRequestRepository.java
  src/main/java/com/highFour/LUMO/friend/service/FriendService.java
Labels: ✨ feature

#26 feat: FCM 알림 세팅
  .gitignore
  build.gradle
  src/main/java/com/highFour/LUMO/common/config/FcmConfig.java
  src/main/java/com/highFour/LUMO/common/exceptionType/NotificationExceptionType.java
  src/main/java/com/highFour/LUMO/diary/service/DiaryService.java
  src/main/java/com/highFour/LUMO/member/entity/Member.java
  src/main/java/com/highFour/LUMO/notification/api/FcmController.java
  src/main/java/com/highFour/LUMO/notification/dto/FcmTokenSaveRequest.java
  src/main/java/com/highFour/LUMO/notification/service/FcmService.java
  src/main/resources/application.yml
Labels: ✨ feature

#28 fix: 회원파트 수정
  src/main/java/com/highFour/LUMO/common/InitialDataLoader.java
  src/main/java/com/highFour/LUMO/friend/dto/FriendListRes.java
  src/main/java/com/highFour/LUMO/member/api/MemberController.java
  src/main/java/com/highFour/LUMO/member/config/SecurityConfig.java
  src/main/java/com/highFour/LUMO/member/dto/MemberInfoRes.java
  src/main/java/com/highFour/LUMO/member/dto/MemberPasswordResetReq.java
  src/main/java/com/highFour/LUMO/member/dto/MemberPasswordUpdateReq.java
  src/main/java/com/highFour/LUMO/member/dto/MemberSignUpReq.java
  src/main/java/com/highFour/LUMO/member/entity/Member.java
  src/main/java/com/highFour/LUMO/member/entity/Role.java
  src/main/java/com/highFour/LUMO/member/jwt/service/JwtService.java
  src/main/java/com/highFour/LUMO/member/login/handler/LoginSuccessHandler.java
  src/main/java/com/highFour/LUMO/member/oauth2/OAuthAttributes.java
  src/main/java/com/highFour/LUMO/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/highFour/LUMO/member/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/highFour/LUMO/member/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/highFour/LUMO/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/highFour/LUMO/member/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/highFour/LUMO/member/service/MemberService.java
Labels: 🛠️ fix

#34 feat: 댓글 및 대댓글 작성 기능 구현
  src/main/java/com/highFour/LUMO/comment/api/CommentController.java
  src/main/java/com/highFour/LUMO/comment/dto/CommentReq.java
  src/main/java/com/highFour/LUMO/comment/dto/CommentRes.java
  src/main/java/com/highFour/LUMO/comment/entity/Comment.java
  src/main/java/com/highFour/LUMO/comment/repository/CommentRepository.java
  src/main/java/com/highFour/LUMO/comment/service/CommentService.java
  src/main/java/com/highFour/LUMO/common/exceptionType/CommentExceptionType.java
  src/main/java/com/highFour/LUMO/diary/service/DiaryService.java
Labels: ✨ feature

#39 fix: 로그인 정보 SecurityContextHolder에서 가져오기 및 fcm 알림 성공 메시지 수정
  src/main/java/com/highFour/LUMO/diary/dto/DiaryCreateReq.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryCreateReqDto.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryListRes.java
  src/main/java/com/highFour/LUMO/diary/dto/DiaryListResDto.java
  src/main/java/com/highFour/LUMO/diary/service/DiaryService.java
  src/main/java/com/highFour/LUMO/notification/api/FcmController.java
Labels: 🛠️ fix

#41 fix: securitycontextholder 수정, delYN 수정,ResponseEntity 수정, 안쓰는 코드 삭제,…
  src/main/java/com/highFour/LUMO/common/InitialDataLoader.java
  src/main/java/com/highFour/LUMO/common/exception/TokenException.java
  src/main/java/com/highFour/LUMO/member/api/MemberController.java
  src/main/java/com/highFour/LUMO/member/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/highFour/LUMO/member/config/SecurityConfig.java
  src/main/java/com/highFour/LUMO/member/entity/DelYn.java
  src/main/java/com/highFour/LUMO/member/entity/Member.java
  src/main/java/com/highFour/LUMO/member/login/handler/LoginSuccessHandler.java
  src/main/java/com/highFour/LUMO/member/service/MemberService.java
  src/main/java/com/highFour/LUMO/member/smtp/api/EmailController.java
  src/main/java/com/highFour/LUMO/member/smtp/service/EmailService.java
Labels: 🐛 bug, 🛠️ fix

#43 fix: api마다 ResponseEntity 메시지 수정
  src/main/java/com/highFour/LUMO/diary/api/DiaryController.java
Labels: 🛠️ fix

#47 chore: Friend 파트 수정
  src/main/java/com/highFour/LUMO/friend/api/FriendController.java
  src/main/java/com/highFour/LUMO/friend/dto/FriendListRes.java
  src/main/java/com/highFour/LUMO/friend/dto/FriendReq.java
  src/main/java/com/highFour/LUMO/friend/dto/FriendRequestReq.java
  src/main/java/com/highFour/LUMO/friend/service/FriendService.java
Labels: ⚙️ chore

#49 chore: Comment 파트 fromEntity / toEntity 메서드 Record 로 변경
  src/main/java/com/highFour/LUMO/comment/api/CommentController.java
  src/main/java/com/highFour/LUMO/comment/dto/CommentReq.java
  src/main/java/com/highFour/LUMO/comment/service/CommentService.java
Labels: ⚙️ chore
